spring:
  application:
    name: store-microservice
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org:
      springframework:
        security: DEBUG