server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server-microservice
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
# http://localhost:13573/hardware-store/api/swagger-ui/index.html#/user-controller