server:
  port: 8281
  servlet:
    context-path: /hardware-store/api/inventory

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hardware_store_db_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: localhost
      port: 6380

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}