spring:
  application:
    name: inventory-microservice
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#  web:
#    resources:
#      static-locations: classpath:/static/,file:./inventory-service/src/main/resources/static/

logging:
  level:
    org:
      springframework:
        security: DEBUG