spring:
  application:
    name: gateway-microservice
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service/issuer

logging:
  level:
    org:
      springframework:
        security: DEBUG

