version: '3.9'
services:
  postgres_db_store:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hardware_store_db
  redis_db:
    image: redis
    ports:
      - "6380:6379"